version: '3.7'
services:
  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    image: 'laravelapp'
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/ssl:/etc/apache2/ssl
      - ./:/var/www/html

  db:
    image: mysql:5.7
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=securerootpassword
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./volume/db:/var/lib/mysql
