version: '3.1'

services:
  #MariaDB
  db:
    build: ./mariadb/.
    image: 'mariadb_own'
    #command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_PASSWORD: 12345
      MYSQL_USER: mortal
      MYSQL_DATABASE: cine
    ports:
      - '3306:3306'
    volumes:
      - mariadb_data:/var/lib/mysql

  #Adminer
  adminer:
    depends_on:
      - db
    image: adminer
    restart: always
    ports:
      - 9191:8080

  # phpmyadmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '9292:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: 12345

volumes:
  mariadb_data: