version: '3.7'

services:

  mongo:
    build: ./mongo
    image: 'own_mongo:latest'
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 12345
      MONGO_INITDB_DATABASE: dbtest
      MONGODB_APPLICATION_DATABASE: dbuser
      MONGODB_APPLICATION_USER: user
      MONGODB_APPLICATION_PASS: 12345
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8088:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: 12345
    depends_on:
      - mongo

volumes:
    mongodb_data:
