version: '3.5'

services:

  mariadb:
    image: "mariadb"
    restart: always
    environment:
      - MARIADB_ROOT_PASSWORD=12345
      - MARIADB_USER=user
      - MARIADB_PASSWORD=12345
    ports:
      - '3307:3306'
    volumes:
      - mariadb_data:/var/lib/mysql
      - mariadb_conf:/etc/mysql
    networks:
      - mariadb_net

  # phpmyadmin
  phpmyadmin:
    depends_on:
      - mariadb
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '9393:80'
    environment:
      PMA_HOST: mariadb
      MYSQL_ROOT_PASSWORD: 12345
    networks:
      - mariadb_net

networks:
  mariadb_net:

volumes:
  mariadb_data: null
  mariadb_conf: null
