 
version: "3.9"
services:
  db:
    image: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=12345
      - MYSQL_DATABASE=palomar_prod
    volumes:
      - ./volume/db:/var/lib/mysql
