services:
  #mysql
  mysql_db:
    container_name: mysql_local
    image: mysql:9.2
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=12345
    volumes:
      - /mnt/linux-storage/docker/volume/mysql_data:/var/lib/mysql
      - /mnt/linux-storage/docker/config/my.cnf:/etc/mysql/conf.d/my.cnf:ro
    networks:
      - mysql_net
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']

  # phpmyadmin
  phpmyadmin:
    container_name: phpmyadmin_local
    depends_on:
      - mysql_db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '9292:80'
    environment:
      PMA_HOST: mysql_db
      MYSQL_ROOT_PASSWORD: 12345
    networks:
      - mysql_net

networks:
  mysql_net: 
      
volumes:
  mysql_data: {}
      
