version: "3.9"

services:
  #mysql
  db:
    image: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=12345
      - MYSQL_DATABASE=my_database_name
    volumes:
      - mysql_data:/var/lib/mysql
      - ./volume/mysql_conf:/etc/mysql/conf.d
    networks:
      - mysql_net
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']

  # phpmyadmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '9292:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: 12345
    networks:
      - mysql_net

networks:
  mysql_net: 
      
volumes:
  mysql_data: {}
      