version: '3'

services:
  
  sqlserver:
    container_name: sqlserver-db
    image: mcr.microsoft.com/mssql/server:2019-latest
    user: root
    environment:
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
      - MSSQL_PID=Developer
    ports:
      - "1433:1433"
    volumes:
      - sqlserver-data:/var/opt/mssql/data
      - sqlserver-secrets:/var/opt/mssql/secrets

volumes:
  sqlserver-data:
  sqlserver-secrets: